# Generated by Django 3.2.4 on 2021-06-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfile_pic',
            new_name='profile_pic',
        ),
    ]
